# Puerto por defecto para MongoDB local
quarkus.mongodb.connection-string = mongodb://localhost:27017

# Base de datos a usar (la crea si no existe)
quarkus.mongodb.database = jjtaxidriver


quarkus.swagger-ui.path=swaggerui
mp.openapi.extensions.smallrye.info.title=JJ TAXI DRIVE
%dev.mp.openapi.extensions.smallrye.info.title=JJ TAXI DRIVE (development)
%test.mp.openapi.extensions.smallrye.info.title=JJ TAXI DRIVE (test)
mp.openapi.extensions.smallrye.info.version=1.0.1
mp.openapi.extensions.smallrye.info.description=Just an example service
mp.openapi.extensions.smallrye.info.termsOfService=Your terms here
mp.openapi.extensions.smallrye.info.contact.email=techsupport@example.com
mp.openapi.extensions.smallrye.info.contact.name=JJ TAXI DRIVE Support
mp.openapi.extensions.smallrye.info.contact.url=http://exampleurl.com/contact
mp.openapi.extensions.smallrye.info.license.name=Apache 2.0
mp.openapi.extensions.smallrye.info.license.url=https://www.apache.org/licenses/LICENSE-2.0.html



# Habilitar Swagger UI en modo prod y compilado nativo
quarkus.swagger-ui.always-include=true

#redis
quarkus.redis.hosts=redis://localhost:6379

# Deshabilita HTTP inseguro
quarkus.http.port=0
# Habilita HTTPS en 8083
quarkus.http.ssl-port=8083
# Escucha en todas las interfaces
quarkus.http.host=0.0.0.0


quarkus.http.ssl.certificate.key-store-file=C:/VSFESAAS_TEST/certificado_wss/keystore.p12
quarkus.http.ssl.certificate.key-store-password=MiPasswordSecreto
quarkus.http.ssl.certificate.key-store-file-type=PKCS12

